export enum AUTH_ACTIONS {
	AUTH_INIT = "AUTH_INIT",
	HANDLE_LOADER = "HANDLE_LOADER",
	REGISTER_SUCCESS = "REGISTER_SUCCESS",
	AUTH_SUCCESS = "AUTH_SUCCESS",
	AUTH_FAILED = "AUTH_FAILED",
	SIGN_OUT = "SIGN_OUT",
}
